package modelo;
// Generated 12-04-2019 04:33:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private Integer idDepartamento;
     private Paises paises;
     private String nombreDepartamento;
     private Set<Municipios> municipioses = new HashSet<Municipios>(0);

    public Departamentos() {
    }

	
    public Departamentos(Paises paises, String nombreDepartamento) {
        this.paises = paises;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamentos(Paises paises, String nombreDepartamento, Set<Municipios> municipioses) {
       this.paises = paises;
       this.nombreDepartamento = nombreDepartamento;
       this.municipioses = municipioses;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Paises getPaises() {
        return this.paises;
    }
    
    public void setPaises(Paises paises) {
        this.paises = paises;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set<Municipios> getMunicipioses() {
        return this.municipioses;
    }
    
    public void setMunicipioses(Set<Municipios> municipioses) {
        this.municipioses = municipioses;
    }




}


