package modelo;
// Generated 12-04-2019 04:33:47 PM by Hibernate Tools 4.3.1



/**
 * Municipios generated by hbm2java
 */
public class Municipios  implements java.io.Serializable {


     private Integer idMunicipio;
     private Departamentos departamentos;
     private String nombreMunicipio;

    public Municipios() {
    }

    public Municipios(Departamentos departamentos, String nombreMunicipio) {
       this.departamentos = departamentos;
       this.nombreMunicipio = nombreMunicipio;
    }
   
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Departamentos getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Departamentos departamentos) {
        this.departamentos = departamentos;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }




}


