package modelo;
// Generated 12-04-2019 04:33:47 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {


     private Integer idPais;
     private String nombrePais;
     private Set<Departamentos> departamentoses = new HashSet<Departamentos>(0);

    public Paises() {
    }

	
    public Paises(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Paises(String nombrePais, Set<Departamentos> departamentoses) {
       this.nombrePais = nombrePais;
       this.departamentoses = departamentoses;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }
    public Set<Departamentos> getDepartamentoses() {
        return this.departamentoses;
    }
    
    public void setDepartamentoses(Set<Departamentos> departamentoses) {
        this.departamentoses = departamentoses;
    }




}


