package com.empresa.model;
// Generated 12-04-2019 09:31:25 AM by Hibernate Tools 4.3.1



/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {


     private Integer idPais;
     private String nombrePais;

    public Paises() {
    }

    public Paises(String nombrePais) {
       this.nombrePais = nombrePais;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }




}


